### ISSUE TITLE
hi,  I have a problem when run this jar,help me ,please.

### ISSUE THREAD

**Issue by lovexqh** [marcelmay/hadoop-hdfs-fsimage-exporter#22]
run script:
java -dsa -da -XX:+UseG1GC -Xmx1024m \
    -jar fsimage-exporter-1.2-new.jar \
    localhost 9092 fsimage.yml
problem:
0 [main] INFO  de.m3y.hadoop.hdfs.hfsa.core.FSImageLoader  - Loaded 2 strings [7ms]
3 [main] INFO  de.m3y.hadoop.hdfs.hfsa.core.FSImageLoader  - Loaded 1 inodes [2ms]
3 [main] INFO  de.m3y.hadoop.hdfs.hfsa.core.FSImageLoader  - Sorted 1 inodes [0ms]
7 [main] INFO  de.m3y.prometheus.exporter.fsimage.FsImageWatcher  - Loaded /home/zwx602706/program/hadoop/tmp/dfs/name/current/fsimage_0000000000000006624 with 0.0MiB in 75ms
50 [main] ERROR de.m3y.prometheus.exporter.fsimage.FsImageWatcher  - Can not preload FSImage
java.lang.NullPointerException
        at de.m3y.hadoop.hdfs.hfsa.core.FSImageLoader.visitParallel(FSImageLoader.java:325)
        at de.m3y.hadoop.hdfs.hfsa.core.FSImageLoader.visitParallel(FSImageLoader.java:311)
        at de.m3y.prometheus.exporter.fsimage.FsImageReporter.computeStatsReport(FsImageReporter.java:303)
        at de.m3y.prometheus.exporter.fsimage.FsImageWatcher.run(FsImageWatcher.java:99)
        at de.m3y.prometheus.exporter.fsimage.FsImageWatcher.getFsImageReport(FsImageWatcher.java:114)
        at de.m3y.prometheus.exporter.fsimage.FsImageCollector.collect(FsImageCollector.java:206)
        at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:100)
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
        at io.prometheus.client.Collector.register(Collector.java:139)
        at io.prometheus.client.Collector.register(Collector.java:132)
        at de.m3y.prometheus.exporter.fsimage.WebServer.configure(WebServer.java:20)
        at de.m3y.prometheus.exporter.fsimage.WebServer.main(WebServer.java:61)
52 [main] ERROR de.m3y.prometheus.exporter.fsimage.FsImageCollector  - FSImage scrape failed
java.lang.NullPointerException
        at de.m3y.prometheus.exporter.fsimage.FsImageWatcher.run(FsImageWatcher.java:103)
        at de.m3y.prometheus.exporter.fsimage.FsImageWatcher.getFsImageReport(FsImageWatcher.java:114)
        at de.m3y.prometheus.exporter.fsimage.FsImageCollector.collect(FsImageCollector.java:206)
        at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:100)
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50)
        at io.prometheus.client.Collector.register(Collector.java:139)
        at io.prometheus.client.Collector.register(Collector.java:132)
        at de.m3y.prometheus.exporter.fsimage.WebServer.configure(WebServer.java:20)
        at de.m3y.prometheus.exporter.fsimage.WebServer.main(WebServer.java:61)
114 [main] INFO  org.eclipse.jetty.server.Server  - jetty-8.y.z-SNAPSHOT
164 [main] INFO  org.eclipse.jetty.server.AbstractConnector  - Started SelectChannelConnector@localhost:9092

**Comment by marcelmay** [comment]
Thx, @lovexqh !

Embarrassing error when FSIMage is empty (0MiB).

Fixed this in https://github.com/marcelmay/hfsa/issues/24 , so an update to https://github.com/marcelmay/hfsa/milestone/4 will resolve this.

As a workaround, you could try to store some data (directories) in HDFS ... so that FSIMage is not empty.
