### ISSUE TITLE
Error run for Hadoop version 3.3.1

### ISSUE THREAD

**Issue by frankie1211** [marcelmay/hadoop-hdfs-fsimage-exporter#49]
docker run -i -t -p 9709:9709 -v /data/dfs/name/current:/fsimage-location -e "JAVA_OPTS=-server -XX:+UseG1GC -Xmx1024m" marcelmay/hadoop-hdfs-fsimage-exporter

2021-08-16 09:51:14,575 [main] INFO  de.m3y.prometheus.exporter.fsimage.WebServer  - FSImage exporter started and listening on http://0.0.0.0:9709
2021-08-16 09:51:14,615 [pool-3-thread-1] ERROR de.m3y.prometheus.exporter.fsimage.FsImageUpdateHandler  - Can not load FSImage /fsimage-location/fsimage_0000000000004734441
java.io.IOException: Unsupported layout version -66
        at org.apache.hadoop.hdfs.server.namenode.FSImageUtil.loadSummary(FSImageUtil.java:78)
        at de.m3y.hadoop.hdfs.hfsa.core.FsImageLoader.load(FsImageLoader.java:286)
        at de.m3y.prometheus.exporter.fsimage.FsImageUpdateHandler.loadFsImage(FsImageUpdateHandler.java:207)
        at de.m3y.prometheus.exporter.fsimage.FsImageUpdateHandler.onFsImageChange(FsImageUpdateHandler.java:185)
        at de.m3y.prometheus.exporter.fsimage.FsImageWatcher.run(FsImageWatcher.java:64)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by marcelmay** [comment]
Thanks alot.

This requires to update the dependencies to Hadoop 3.3.x (which comes with [hfsa](https://github.com/marcelmay/hfsa/releases/tag/release-1.3.3)).

https://github.com/apache/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/NameNodeLayoutVersion.java#L93

**Comment by marcelmay** [comment]
Should be fixed by #50 .

You could try by building from source, or wait till I release 1.4.2 in the next one or two days.

**Comment by frankie1211** [comment]
> Should be fixed by #50 .
> 
> You could try by building from source, or wait till I release 1.4.2 in the next one or two days.

@marcelmay really appreciate all your effort, thanks!!
